package com.insight.quantlife.tests;
import android.app.*;import android.os.Bundle;import com.insight.quantlife.*;import org.json.*;import java.util.*;
public class ArticleReadTest extends Instrumentation {
 int passed;void check(boolean b,String s)throws Exception{if(!b)throw new Exception(s);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+s+"\n");sendStatus(0,o);}
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 final String url="https://mp.weixin.qq.com/s/4I7QzzT5_mGdubyN1FKObA";
 JSONObject searchSchema()throws Exception{return new JSONObject("{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"},\"objective\":{\"type\":\"string\"},\"numResults\":{\"type\":\"number\"}},\"required\":[\"query\",\"objective\"]}");}
 JSONObject fetchSchema()throws Exception{return new JSONObject("{\"type\":\"object\",\"properties\":{\"urls\":{\"type\":\"array\"},\"maxCharacters\":{\"type\":\"number\"}},\"required\":[\"urls\"]}");}
 JSONObject text(String body)throws Exception{return new JSONObject().put("content",new JSONArray().put(new JSONObject().put("type","text").put("text",body)));}
 String prose(){StringBuilder b=new StringBuilder();for(int i=0;i<40;i++)b.append("公开正文：数据质量、业务知识与技术落地是必要条件。\n");return b.toString();}
 ExaMcp.Reply reply(JSONObject q,JSONObject result)throws Exception{return new ExaMcp.Reply(200,"application/json","session",new JSONObject().put("jsonrpc","2.0").put("id",q.getInt("id")).put("result",result).toString());}
 ExaMcp fixture(boolean failFetch,List<JSONObject> requests)throws Exception{return new ExaMcp((q,s,p,d)->{requests.add(q);String method=q.getString("method");if(method.equals("initialize"))return reply(q,new JSONObject().put("protocolVersion","2024-11-05"));if(method.equals("notifications/initialized"))return new ExaMcp.Reply(202,"","","");if(method.equals("tools/list"))return reply(q,new JSONObject().put("tools",new JSONArray().put(new JSONObject().put("name","web_search_exa").put("inputSchema",searchSchema())).put(new JSONObject().put("name","web_fetch_exa").put("inputSchema",fetchSchema()))));JSONObject params=q.getJSONObject("params");if(params.getString("name").equals("web_fetch_exa")){check(params.getJSONObject("arguments").getJSONArray("urls").getString(0).equals(url),"Fetch sends clean original URL, not challenge redirect");check(params.getJSONObject("arguments").length()==2&&!params.toString().contains("apiKey"),"Fetch sends no model/Tavily Key or personal data");return reply(q,failFetch?new JSONObject().put("isError",true).put("content",new JSONArray()):text("# 企业大数据如何变成利润？\nURL: "+url+"\n\n"+prose()));}check(params.getString("name").equals("web_search_exa"),"Only allowlisted read/search tool used");return reply(q,text("Title: 搜索标题\nURL: "+url+"\nAuthor: N/A\nHighlights:\n搜索摘要不等于正文"));});}
 @Override public void onStart(){Bundle out=new Bundle();try{
  JSONObject args=ExaMcp.fetchArguments(url,fetchSchema());check(args.getInt("maxCharacters")==5000&&args.getJSONArray("urls").length()==1,"Bounded single-URL fetch schema");
  JSONObject page=ExaMcp.parsePage(text("# 正文标题\nURL: "+url+"\n\n"+prose()),url);check(page.getString("title").equals("正文标题")&&page.getString("contentStatus").equals("limited_text"),"MCP read title/body parsed with limited-text provenance");
  for(String raw:new String[]{"# 其他页\nURL: https://example.com/other\n\n"+prose(),"# 环境异常\nURL: "+url+"\n\n验证", "Title: 搜索标题\nURL: "+url+"\nHighlights: "+prose()}){boolean rejected=false;try{ExaMcp.parsePage(text(raw),url);}catch(ExaMcp.Failure e){rejected=true;}check(rejected,"Unrelated/insufficient/search-format read body rejected");}
  page=ExaMcp.parsePage(text("# 长文章\nURL: "+url+"\n\n"+prose()+prose()+prose()+prose()+prose()+prose()),url);check(page.getString("excerpt").length()==5000&&page.getBoolean("textTruncated"),"Oversized article locally truncated to5000 chars");
  List<JSONObject> requests=new ArrayList<>();ExaMcp exa=fixture(false,requests);LinkReader r=new LinkReader((u,d)->new LinkReader.Page(302,"https://mp.weixin.qq.com/mp/wappoc_appmsgcaptcha?poc_token=temporary-private-value","",new byte[0]),null,exa);JSONObject found=r.resolve(url,null);
  check(found.getString("status").equals("metadata")&&found.getString("readMethod").equals("exa_fetch")&&found.getString("contentType").equals("article"),"WeChat challenge recovers using same-link Exa limited body");check(found.getString("directStatus").equals("verification_required")&&!found.toString().contains("temporary-private-value"),"Challenge target/token never retained or sent to search");check(requests.size()==4,"Successful read does not make extra search call");
  int n=requests.size();r.resolve(url,null);check(requests.size()==n,"Exa read cached without additional network request");
  requests=new ArrayList<>();r=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),null,fixture(true,requests));found=r.resolve(url,null);check(found.getString("status").equals("search_match")&&found.getString("contentStatus").equals("metadata_only"),"Unreadable Exa body falls back to search metadata only");check(requests.size()==5&&found.getString("fetchStatus").equals("tool_error"),"Read then search share one initialization, bounded extra call");
  r=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),null,exa);found=r.resolve(url,new JSONObject().put("provider","exa").put("enabled",false));check(found.getString("status").equals("unavailable")&&!found.has("fetchStatus"),"Disabled search setting also blocks external MCP reading");
  out.putString("stream","PASS: "+passed+" article read synthetic checks\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e);finish(Activity.RESULT_CANCELED,out);}}
}
