package com.insight.quantlife.tests;
import android.app.*;import android.os.Bundle;import com.insight.quantlife.*;import org.json.*;
/** Public article only; model interaction is synthetic and stays on localhost. */
public class ArticleLiveTest extends Instrumentation {
 int passed;void check(boolean b,String s)throws Exception{if(!b)throw new Exception(s);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+s+"\n");sendStatus(0,o);}
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 @Override public void onStart(){Bundle out=new Bundle();try{
  String url="https://mp.weixin.qq.com/s/4I7QzzT5_mGdubyN1FKObA";long time=System.currentTimeMillis();JSONObject source=new LinkReader().resolve(url,new JSONObject().put("provider","exa").put("enabled",true));check(source.getString("readMethod").equals("exa_fetch")&&source.getString("title").equals("企业大数据如何变成利润？"),"Real Android clean WeChat URL recovered by anonymous Exa read");check(source.getString("excerpt").contains("数据质量")&&source.getString("contentType").equals("article"),"Same article body returned, not related books/search hits");
  MainHost h=new MainHost(this);h.open();JSONObject init=(JSONObject)h.call("init",new JSONObject());int count=init.getJSONArray("records").length();JSONObject previous=init.getJSONObject("settings").getJSONObject("linkSearch");h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider","exa").put("enabled",true)));h.call("saveSettings",new JSONObject().put("settings",new JSONObject().put("profile",new JSONObject().put("id","custom").put("label","synthetic article QA").put("baseUrl","http://127.0.0.1:8790/v1").put("model","dummy-model").put("apiKey","local-test-only-not-a-real-key").put("protocol","chat").put("allowHttp",true))));
  h.js("window.__articleReload='old';location.reload()");for(int i=0;i<80;i++){if(h.js("typeof window.__articleReload").equals("\"undefined\""))break;Thread.sleep(100);}h.waitText("今天的投入");
  String note="是一篇企业数据驱动转型的文章，文章强调，第一需要做好数据治理和数据质量，第二需要懂业务、懂数据、懂技术的团队协作。";String input=url+note;
  h.js("window.__qaOriginal=LifeNative;window.__articleRequests=[];window.LifeNative={call:function(action,payload,id){window.__articleRequests.push({action,data:JSON.parse(payload)});window.__qaOriginal.call(action,payload,id);}};document.querySelector('[data-page=chat]').click();document.querySelector('#chat-input').value="+JSONObject.quote(input)+";document.querySelector('[data-action=send]').click()");check(h.waitText("允许读取这些公开链接"),"Actual UI asks consent for clean article URL");h.js("document.querySelector('#confirm-ok').click()");boolean done=false;for(int i=0;i<500;i++){if(h.js("document.querySelectorAll('.candidate').length").equals("1")){done=true;break;}Thread.sleep(100);}check(done,"Actual native read and synthetic LLM produce one confirmed-source draft");check(new JSONArray("["+h.js("window.__articleRequests.filter(x=>x.action==='readLinks')[0].data.urls[0]")+"]").getString(0).equals(url),"Chinese description not appended to outgoing URL");
  String text=h.js("document.querySelectorAll('.message-content')[document.querySelectorAll('.message-content').length-1].innerText");check(text.length()<220&&!text.contains("全部历史")&&!text.contains("熟练度")&&!text.contains("平台分布"),"Irrelevant mock answer suppressed by purpose-specific record presenter");check(h.js("document.querySelector('.candidate').innerText").contains("企业大数据如何变成利润？")&&h.js("document.querySelector('.candidate').innerText").contains("0分钟"),"Reliable original title and zero unspecified time shown");check(h.js("document.querySelector('.candidate').innerText").contains("文章强调")&&!h.js("document.querySelector('.candidate').innerText").contains("网上摘要被模型"),"Provided annotations retained, website text not personal note");check(h.js("window.__articleRequests.filter(x=>x.action==='ask').length").equals("1"),"Article recording bypasses unrelated history-planning model request");check(h.js("window.__articleRequests.filter(x=>x.action==='ask').every(x=>!x.data.messages[0].content.includes('learningMinutes'))").equals("true"),"No all-life statistics in article recording system context");check(h.js("document.querySelector('.link-diagnostics').open").equals("false"),"Read diagnostics collapsed by default");check(((JSONObject)h.call("init",new JSONObject())).getJSONArray("records").length()==count,"Reading and concise reply do not silently insert database records");h.js("document.querySelector('.candidate').scrollIntoView({block:'center'})");h.screenshot("article-purpose-1.4.2.png");h.js("document.querySelector('[data-remove-candidate]').click()");h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider",previous.getString("provider")).put("enabled",previous.getBoolean("enabled"))));out.putString("stream","PASS: "+passed+" real article/Android UI checks; "+(System.currentTimeMillis()-time)+"ms total; no real model Key used\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e);finish(Activity.RESULT_CANCELED,out);}}
}
