package com.insight.quantlife.tests;
import android.app.Activity;import android.app.Instrumentation;import android.os.Bundle;import org.json.*;import com.insight.quantlife.*;import java.io.*;
public class BridgeOverlayTest extends Instrumentation{
 MainHost host;int passed;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean b,String s)throws Exception{if(!b)throw new Exception(s);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+s+"\n");sendStatus(0,o);}
 @Override public void onStart(){Bundle out=new Bundle();try(TrackStore db=new TrackStore(getTargetContext())){
  StringBuilder text=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(getTargetContext().openFileInput("bridge-upgrade-fixture.json"),"UTF-8"))){String s;while((s=r.readLine())!=null)text.append(s);}JSONObject snap=new JSONObject(text.toString());host=new MainHost(this);host.open();JSONObject init=(JSONObject)host.call("init",new JSONObject());
  check(init.getJSONArray("records").toString().equals(snap.getJSONArray("records").toString()),"Cover upgrade preserves learning/work content");check(init.getJSONArray("wikiPages").toString().equals(snap.getJSONArray("wiki").toString()),"Cover upgrade preserves Wiki");check(init.getJSONObject("settings").toString().equals(snap.getJSONObject("settings").toString()),"Cover upgrade preserves model settings and key-configured state");
  String date="2026-10-17";JSONObject day=db.day(date);JSONArray points=day.getJSONArray("points");check(db.getReadableDatabase().getVersion()==3&&day.getInt("filterVersion")==4,"Overlay does not change track schema or filtering rules");check(db.diagnostics(date).getJSONArray("rawPoints").toString().equals(snap.getJSONArray("raw").toString()),"Raw GPS bytes remain semantically identical");check(db.gpx(date).equals(snap.getString("gpx")),"Ordinary GPX content exactly unchanged by overlay");check(host.js("LifeTracks.summary("+points+").meters").equals("90"),"Only90m recorded legs counted,90m virtual bridge excluded");check(host.js("LifeTracks.summary("+points+").segments").equals("3"),"Recorded segments remain separated");check(host.js("LifeTracks.bridges("+points+").length").equals("1"),"GPS-assisted short gap eligible,218-second gap rejected");check(points.getJSONObject(1).has("reportedSpeed")&&points.getJSONObject(1).has("speedAccuracy"),"Original GPS speed and uncertainty available for auxiliary checks");
  host.js("localStorage.removeItem('zhishi-track-inferred-bridges');window.__bridgeStrokes=[];window.__originalStroke=CanvasRenderingContext2D.prototype.stroke;CanvasRenderingContext2D.prototype.stroke=function(){if(this.canvas.id==='track-map')window.__bridgeStrokes.push({style:this.strokeStyle,dash:this.getLineDash()});return window.__originalStroke.apply(this,arguments)};document.querySelector('[data-page=tracks]').click()");host.waitText("每天走过的地方");host.js("document.querySelector('#track-date').value='2026-10-17';document.querySelector('#track-date').dispatchEvent(new Event('change'))");check(host.waitText("显示 1 处短缺口参考"),"Actual WebView labels display-only inferred connection");check(host.js("document.querySelector('#track-show-bridges').checked").equals("true"),"Overlay defaults enabled");check(host.js("window.__bridgeStrokes.some(s=>s.style==='#8754a1'&&s.dash.join(',')==='7,5')").equals("true"),"Canvas draws purple dashed inference layer");check(host.js("window.__bridgeStrokes.some(s=>s.style==='#216a54'&&s.dash.length===0)").equals("true"),"Recorded green lines remain solid");check(host.waitText("0.09"),"Visible distance remains0.09km with bridge on");
  host.js("document.querySelector('#track-gap-list').open=true;document.querySelector('[data-track-gap=\"0\"]').click()");check(host.js("document.querySelector('#track-selected-point').innerText").contains("未计入里程"),"Focused gap explicitly discloses inference and no distance accumulation");host.js("document.querySelector('#track-show-bridges').focus();document.querySelector('#track-map').scrollIntoView({block:'center'});setTimeout(()=>document.querySelector('#track-map').scrollIntoView({block:'center'}),400)");host.screenshot("bridge-overlay.png");
  host.js("window.__bridgeStrokes=[];document.querySelector('#track-show-bridges').checked=false;document.querySelector('#track-show-bridges').dispatchEvent(new Event('change'))");check(host.waitText("已关闭；符合条件"),"User can disable inferred overlay");check(host.js("window.__bridgeStrokes.every(s=>s.dash.length===0)").equals("true"),"Overlay off produces no dashed strokes");check(host.waitText("0.09"),"Turning overlay off does not change mileage");check(host.js("localStorage.getItem('zhishi-track-inferred-bridges')").equals("\"off\""),"Only display preference stored locally");
  host.js("document.querySelector('#track-refresh').click()");Thread.sleep(400);check(host.js("document.querySelector('#track-show-bridges').checked").equals("false"),"Refresh preserves overlay preference");check(db.gpx(date).equals(snap.getString("gpx"))&&db.diagnostics(date).getJSONArray("rawPoints").toString().equals(snap.getJSONArray("raw").toString()),"Toggle and drawing never mutate raw GPS or ordinary GPX");check(!((JSONObject)host.call("init",new JSONObject())).has("points"),"Position data still absent from AI initialization");
  host.js("document.querySelector('#track-show-bridges').checked=true;document.querySelector('#track-show-bridges').dispatchEvent(new Event('change'))");check(host.waitText("显示 1 处短缺口参考"),"Overlay can be re-enabled");
  out.putString("stream","PASS: "+passed+" cover-upgrade and inferred-overlay checks.\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e+"\n");finish(Activity.RESULT_CANCELED,out);}}
}
