const {test}=require('node:test'),assert=require('node:assert/strict');
const C=require('../app/src/main/assets/conversation.js'),L=require('../app/src/main/assets/links.js');
const clean='https://mp.weixin.qq.com/s/4I7QzzT5_mGdubyN1FKObA';
const input='我\n'+clean+'是一篇指导企业转型为数据驱动的书籍概述文章，文章强调，想要让企业从数据沙漠到价值绿洲，第一，需要从数据治理上入手；第二，懂业务、懂数据、懂技术落地三者齐备。';
const source={url:clean,title:'企业大数据如何变成利润？',status:'metadata',readMethod:'exa_fetch',contentStatus:'limited_text',excerpt:'原文中的更多内容，不是我的笔记',platform:'微信公众号',contentType:'article'};
const record={id:'a',type:'learning',date:'2026-10-07',title:source.title,url:clean,note:'模型改写',durationMinutes:99,platform:'微信公众号',tags:[]};
test('WeChat URL immediately followed by Chinese description extracts only content ID',()=>assert.deepEqual(L.extract(input),[clean]));
test('Chinese annotations are not discarded or mistaken for bare-link input',()=>{assert.equal(L.bare(input),false);assert.match(L.annotations(input),/文章强调/);assert.match(L.annotations(input),/数据治理/);});
test('Generic real Chinese paths are not globally truncated',()=>{assert.deepEqual(L.extract('https://example.com/中文文章'),['https://example.com/中文文章']);assert.deepEqual(L.extract('https://mp.weixin.qq.com/s/'+encodeURIComponent('中文路径')),['https://mp.weixin.qq.com/s/'+encodeURIComponent('中文路径')]);});
test('Known WeChat ASCII URL and percent encoded query remain intact',()=>{const url=clean+'?scene=1&name=%E4%B8%AD';assert.deepEqual(L.extract(url),[url]);});
test('New article notes infer record purpose without historical planner',()=>{const p=C.directPlan(input);assert.equal(p.intent,'record');assert.equal(p.topic,'');});
test('Explicit article summary infers question not record',()=>{assert.equal(C.directPlan('请总结 '+clean).purpose,'article');assert.equal(C.directPlan(clean+' 这篇是什么意思？').intent,'general');});
test('Explicit personal history request still goes to history retrieval planner',()=>assert.equal(C.directPlan('我的历史笔记有没有 '+clean),null));
test('Record context never contains all-life totals, daily series or mastery data',()=>{const c=C.focusedContext([record],[],input,C.directPlan(input),[source]);assert.equal(c.summary,undefined);assert.equal(c.topicSummary,undefined);assert.equal(c.dailySeries,undefined);assert.deepEqual(c.records,[]);assert.equal(c.duplicateCandidates.length,1);});
test('Article questions cannot receive unrelated local notes or statistical context',()=>{const c=C.focusedContext([record],[],'请总结 '+clean,C.directPlan('请总结 '+clean),[source]);assert.deepEqual(c.records,[]);assert.deepEqual(c.availableCitationIds,[]);assert.equal(c.summary,undefined);});
test('User supplied annotations preserved verbatim, invented time and web snippets excluded',()=>{const r=L.guardRecords([record],[source],input)[0];assert.equal(r.durationMinutes,0);assert.equal(r.note,L.annotations(input));assert.ok(!r.note.includes('原文中的更多内容'));});
test('A summary instruction containing article keywords is not a personal note',()=>assert.equal(L.annotations('请总结 '+clean+'。文章强调数据治理，第一做好质量管理。'+'其他'.repeat(30)),''));
test('Record reply states actual accepted count, never the model claimed count',()=>{assert.match(C.recordReply([],[]),/尚未生成/);assert.match(C.recordReply([record],[source]),/1条/);assert.ok(C.recordReply([record],[source]).length<150);});
test('Record reply contains no irrelevant statistics or mastery headings',()=>assert.doesNotMatch(C.recordReply([record],[source]),/全部历史|平台分布|熟练度|主题小结/));
test('Fresh article inputs exclude prior long assistant summaries',()=>assert.deepEqual(C.recent([{role:'assistant',text:'历史统计'.repeat(100)}],C.directPlan(input)),[]));
test('Focused prompt explicitly forbids unrelated material and fabricated original titles',()=>{const p=C.prompt(C.directPlan(input),input,'2026-10-07',{});assert.match(p,/禁止附加全部历史统计/);assert.match(p,/不生成占位标题/);});
test('Read provenance distinguishes limited Exa text from metadata-only search',()=>{assert.match(L.sourceLabel(source),/有限正文/);assert.match(L.sourceLabel({...source,readMethod:'search',status:'search_match'}),/不是正文/);});
test('Stored diagnostics are bounded metadata, not raw external page bodies',()=>{const d=C.diagnostics([source])[0];assert.equal(d.excerpt,undefined);assert.equal(d.readMethod,'exa_fetch');});
test('History date calculation and topic insights remain available when requested',()=>{const c=C.focusedContext([record],[],'2026-10-07学习多久',{intent:'history',topic:'',keywords:[],dateStart:'',dateEnd:''},[],new Date('2026-10-07T12:00:00'));assert.equal(c.summary.learningMinutes,99);assert.equal(c.dailySeries,undefined);});
