package com.insight.quantlife.tests;
import android.app.*;import android.os.Bundle;import com.insight.quantlife.*;import org.json.*;
/** Opt-in public network smoke test; no model request, keys, private locations or notes. */
public class ExaLiveTest extends Instrumentation {
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 @Override public void onStart(){Bundle out=new Bundle();try{
  String url="https://www.bilibili.com/video/BV164411b7dx/";long start=System.currentTimeMillis();
  JSONArray hits=LinkReader.searchResults(new ExaMcp().search(url));JSONObject result=new JSONObject();for(int i=0;i<hits.length();i++){JSONObject hit=hits.getJSONObject(i);if(LinkReader.samePage(url,hit.getString("url"))){result.put("status","search_match").put("title",hit.getString("title")).put("contentType",LinkReader.parse("",url).getString("contentType"));break;}}
  if(!result.optString("status").equals("search_match")||!result.optString("title").contains("吴恩达")||!result.optString("contentType").equals("video"))throw new Exception(result.toString());
  Bundle progress=new Bundle();progress.putString("stream","PASS real Android anonymous Exa HTTP MCP exact Bilibili title/type, no Key; "+(System.currentTimeMillis()-start)+"ms; "+result.optString("title")+"\n");sendStatus(0,progress);
  MainHost h=new MainHost(this);h.open();JSONObject init=(JSONObject)h.call("init",new JSONObject());int count=init.getJSONArray("records").length();JSONObject previous=init.getJSONObject("settings").getJSONObject("linkSearch");h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider","exa").put("enabled",true)));
  h.js("window.__exaLiveReload='old';location.reload()");for(int i=0;i<80;i++){if(h.js("typeof window.__exaLiveReload").equals("\"undefined\""))break;Thread.sleep(100);}h.waitText("今天的投入");h.js("document.querySelector('[data-page=chat]').click();document.querySelector('#chat-input').value="+JSONObject.quote(url)+";document.querySelector('[data-action=send]').click()");if(!h.waitText("允许读取这些公开链接"))throw new Exception("No privacy consent");h.js("document.querySelector('#confirm-ok').click()");
  boolean ready=false;for(int i=0;i<500;i++){if(h.js("document.querySelectorAll('.candidate').length").equals("1")){ready=true;break;}Thread.sleep(100);}if(!ready)throw new Exception("Live draft failed: "+h.js("document.body.innerText"));String draft=h.js("document.querySelector('.candidate').innerText");if(!draft.contains("吴恩达")||!draft.contains("视频")||!draft.contains("0分钟"))throw new Exception("Wrong live draft: "+draft);if(((JSONObject)h.call("init",new JSONObject())).getJSONArray("records").length()!=count)throw new Exception("Live draft silently inserted record");h.js("document.querySelector('.candidate').scrollIntoView({block:'center'})");h.screenshot("exa-live-candidate.png");h.js("document.querySelector('[data-remove-candidate]').click()");h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider",previous.getString("provider")).put("enabled",previous.getBoolean("enabled"))));
  out.putString("stream","PASS real Android UI link → consent → live native read/search → correct video draft, zero duration/empty note, no database write\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL live public Exa test: "+e);finish(Activity.RESULT_CANCELED,out);}}
}
