package com.insight.quantlife.tests;
import android.app.*;import android.os.Bundle;import com.insight.quantlife.*;import org.json.*;import java.net.*;import java.util.*;
public class ExaMcpTest extends Instrumentation {
 int passed;void check(boolean b,String s)throws Exception{if(!b)throw new Exception(s);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+s+"\n");sendStatus(0,o);}
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 JSONObject schema()throws Exception{return new JSONObject("{\"type\":\"object\",\"properties\":{\"query\":{\"type\":\"string\"},\"objective\":{\"type\":\"string\"},\"numResults\":{\"type\":\"number\"}},\"required\":[\"query\",\"objective\"],\"additionalProperties\":false}");}
 JSONObject content(String title,String url)throws Exception{return new JSONObject().put("content",new JSONArray().put(new JSONObject().put("type","text").put("text","Title: "+title+"\nURL: "+url+"\nPublished: N/A\nAuthor: test uploader\nHighlights:\n网页摘要；不是用户笔记。\nURL: https://evil.example/")));}
 ExaMcp.Reply reply(JSONObject request,JSONObject result)throws Exception{return new ExaMcp.Reply(200,"application/json","fixture-session",new JSONObject().put("jsonrpc","2.0").put("id",request.getInt("id")).put("result",result).toString());}
 ExaMcp client(String title,String url,List<JSONObject> calls)throws Exception{return new ExaMcp((rpc,s,p,d)->{calls.add(rpc);check(d>System.currentTimeMillis(),"MCP request bounded deadline");String m=rpc.getString("method");if(m.equals("initialize")){check(s.isEmpty(),"Initialization has no credentials/session");check(rpc.getJSONObject("params").length()==3,"Initialization only protocol/capabilities/client info");return reply(rpc,new JSONObject().put("protocolVersion","2024-11-05"));}check(s.equals("fixture-session"),"Negotiated session propagated");if(m.equals("notifications/initialized")){check(!rpc.has("id"),"Initialization notification has no ID");return new ExaMcp.Reply(202,"","","");}if(m.equals("tools/list"))return reply(rpc,new JSONObject().put("tools",new JSONArray().put(new JSONObject().put("name","agent_run").put("inputSchema",schema())).put(new JSONObject().put("name","web_search_exa").put("inputSchema",schema()))));check(m.equals("tools/call")&&rpc.getJSONObject("params").getString("name").equals("web_search_exa"),"Only whitelisted search tool invoked");JSONObject a=rpc.getJSONObject("params").getJSONObject("arguments");check(a.length()==3&&a.getInt("numResults")==3&&!a.has("apiKey")&&!a.has("records")&&!a.has("messages"),"Search arguments contain no keys or personal context");check(a.getString("objective").contains("不要推断"),"Required objective supplied, no invented learning");return reply(rpc,content(title,url));});}
 void rejectDecode(String raw,String mime,int id)throws Exception{boolean failed=false;try{ExaMcp.decode(raw,mime,id);}catch(Exception e){failed=true;}check(failed,"Malformed/unexpected MCP reply rejected");}
 @Override public void onStart(){Bundle out=new Bundle();try{
  check(LinkReader.searchSettings(null).getString("provider").equals("exa")&&LinkReader.searchSettings(null).getBoolean("enabled"),"New install defaults to Exa keyless fallback");
  JSONObject legacy=LinkReader.searchSettings(new JSONObject().put("enabled",false).put("apiKey","dummy"));check(legacy.getString("provider").equals("tavily")&&!legacy.getBoolean("enabled")&&legacy.getString("apiKey").equals("dummy"),"Legacy provider, opt-out and encrypted key retained");
  JSONObject args=ExaMcp.arguments("https://example.com/a",schema());check(args.getString("query").equals("https://example.com/a")&&args.has("objective"),"Discovered current schema supports required objective");
  JSONObject changed=schema().put("required",new JSONArray().put("query").put("unknownRequired"));boolean incompatible=false;try{ExaMcp.arguments("https://example.com/a",changed);}catch(ExaMcp.Failure e){incompatible=e.status.equals("protocol_error");}check(incompatible,"New required server parameter fails closed");
  String json="{\"jsonrpc\":\"2.0\",\"id\":7,\"result\":{\"ok\":true}}";
  check(ExaMcp.decode(json,"application/json; charset=utf-8",7).getJSONObject("result").getBoolean("ok"),"JSON reply decoded");
  check(ExaMcp.decode(": keepalive\r\nevent: message\r\ndata: {\"jsonrpc\":\"2.0\",\"method\":\"notifications/tools/list_changed\"}\r\n\r\nevent: message\r\ndata: "+json+"\r\n\r\n","text/event-stream",7).getJSONObject("result").getBoolean("ok"),"SSE comments, CRLF and notifications safely skipped");
  check(ExaMcp.decode("data: {\"jsonrpc\":\"2.0\",\"id\":7,\n"+"data: \"result\":{\"ok\":true}}\n\n","text/event-stream",7).has("result"),"Multi-line SSE data decoded");
  rejectDecode(json,"text/html",7);rejectDecode(json,"application/json",8);rejectDecode("data: not-json\n\n","text/event-stream",7);rejectDecode("{\"id\":7,\"result\":{}}","application/json",7);
  char[] huge=new char[270000];Arrays.fill(huge,'x');rejectDecode(new String(huge),"application/json",7);
  JSONArray rows=ExaMcp.parseSearch(content("标题", "https://example.com/article/1"));check(rows.length()==1&&rows.getJSONObject(0).getString("url").equals("https://example.com/article/1"),"Header URL parsed, URL inside highlights never promoted");
  check(ExaMcp.parseSearch(content("unsafe","http://127.0.0.1/")).length()==0,"Private result URL discarded");
  check(ExaMcp.parseSearch(content("unsafe","https://example.com/?token=secret")).length()==0,"Credential-bearing result URL discarded");
  check(ExaMcp.parseSearch(new JSONObject().put("content",new JSONArray().put(new JSONObject().put("type","text").put("text","No results found")))).length()==0,"No results is not a fabricated title");
  List<JSONObject> calls=new ArrayList<>();ExaMcp exa=client("免Key标题","https://example.com/article/1",calls);int[] tavily={0};
  LinkReader reader=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),(q,k)->{tavily[0]++;throw new Exception("No paid fallback allowed");},exa);
  JSONObject result=reader.resolve("https://example.com/article/1",null);check(result.getString("status").equals("search_match")&&result.getString("searchProvider").equals("exa")&&result.getString("title").equals("免Key标题"),"Exa integrates with same-link title fallback without Key");check(tavily[0]==0&&calls.size()==4,"Only anonymous initialization/list/search, no Tavily fallback");check(!result.has("note")&&!result.has("durationMinutes")&&result.getString("author").isEmpty(),"Search never invents note/time or confuses uploader with author");
  int before=calls.size();reader.resolve("https://example.com/article/1",null);check(calls.size()==before,"Same public URL served from bounded ten-minute cache");
  reader.resolve("https://example.com/article/1",new JSONObject().put("provider","exa").put("enabled",false));check(calls.size()==before,"Search disabled prevents even cached search use");
  LinkReader direct=new LinkReader((u,d)->new LinkReader.Page(200,"","text/html","<title>直接标题</title>".getBytes("UTF-8")),null,exa);check(direct.resolve("https://example.com/article/1",null).getString("status").equals("metadata")&&calls.size()==before,"Direct metadata wins without invoking Exa");
  LinkReader unrelated=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),null,client("另一页","https://example.com/other",new ArrayList<>()));check(unrelated.resolve("https://example.com/article/1",null).getString("title").isEmpty(),"Related but different result cannot replace original title");
  int[] rateCalls={0};ExaMcp limited=new ExaMcp((q,s,p,d)->{rateCalls[0]++;return new ExaMcp.Reply(429,"application/json","", "secret error");});LinkReader rateReader=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),null,limited);
  result=rateReader.resolve("https://example.com/article/rate",null);check(result.getString("searchStatus").equals("rate_limited")&&result.getString("message").contains("两分钟")&&!result.toString().contains("secret"),"429 is actionable, redacted and not retried");rateReader.resolve("https://example.com/article/rate",null);check(rateCalls[0]==1,"429 cooldown prevents repeated network requests");
  for(String status:new String[]{"timeout","authentication_required","protocol_error","tool_error","response_too_large"}){LinkReader failed=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),null,new ExaMcp((q,s,p,d)->{throw new ExaMcp.Failure(status);}));result=failed.resolve("https://example.com/article/error",null);check(result.getString("searchStatus").equals(status)&&result.getString("title").isEmpty(),"Search failure remains manual-recordable: "+status);}
  ExaMcp timeout=new ExaMcp((q,s,p,d)->{throw new SocketTimeoutException("private detail");});boolean timed=false;try{timeout.search("https://example.com/a");}catch(ExaMcp.Failure e){timed=e.status.equals("timeout");}check(timed,"Network timeout classified without leaking details");
  check(LinkReader.parse("","https://m.douban.com/book/subject/36077485/").getString("contentType").equals("book"),"Mobile Douban book classification");check(LinkReader.parse("","https://read.douban.com/ebook/619994084/").getString("contentType").equals("book"),"Douban ebook classification");
  MainHost h=new MainHost(this);h.open();JSONObject oldSettings=(JSONObject)h.call("getSettings",new JSONObject());JSONObject oldSearch=oldSettings.getJSONObject("linkSearch");check(!oldSearch.has("apiKey"),"Public settings do not expose search secrets");
  h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider","exa").put("enabled",true)));JSONObject saved=(JSONObject)h.call("getSettings",new JSONObject());check(saved.getJSONObject("linkSearch").getString("provider").equals("exa"),"Native bridge saves Exa without entering a Key");
  h.js("window.__exaReload='old';location.reload()");for(int i=0;i<80;i++){if(h.js("typeof window.__exaReload").equals("\"undefined\""))break;Thread.sleep(100);}h.waitText("今天的投入");h.js("document.querySelector('[data-page=settings]').click()");check(h.waitText("Exa 匿名 MCP"),"Phone settings show Exa provider");check(h.js("document.querySelector('#link-search-provider').value").equals("\"exa\"")&&h.js("getComputedStyle(document.querySelector('#tavily-settings')).display").equals("\"none\""),"Exa mode hides Tavily secret field");h.js("document.querySelector('#link-settings-form').closest('.panel').scrollIntoView({block:'start'})");h.screenshot("exa-settings.png");
  h.js("document.querySelector('#link-search-provider').value='tavily';document.querySelector('#link-search-provider').dispatchEvent(new Event('change'))");check(!h.js("getComputedStyle(document.querySelector('#tavily-settings')).display").equals("\"none\""),"Tavily field shown only when selected");
  h.js("document.querySelector('#link-search-provider').value='exa';document.querySelector('#link-search-provider').dispatchEvent(new Event('change'));document.querySelector('#link-settings-form').dispatchEvent(new Event('submit',{cancelable:true}))");check(h.waitText("搜索设置已加密保存"),"Exa phone settings save without Key");
  h.js("document.querySelector('[data-page=chat]').click();document.querySelector('#chat-input').value='https://example.com/';document.querySelector('[data-action=send]').click()");check(h.waitText("允许读取这些公开链接")&&h.js("document.querySelector('#confirm-message').textContent").contains("Exa匿名MCP"),"Consent names current Exa recipient before network");h.js("document.querySelector('#confirm-cancel').click()");
  h.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("provider",oldSearch.getString("provider")).put("enabled",oldSearch.getBoolean("enabled"))));check(((JSONObject)h.call("getSettings",new JSONObject())).getJSONObject("linkSearch").getString("provider").equals(oldSearch.getString("provider")),"Previous settings restored after synthetic test");
  out.putString("stream","PASS: "+passed+" Exa MCP/Android synthetic checks\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e);finish(Activity.RESULT_CANCELED,out);}}
}
