package com.insight.quantlife.tests;
import android.app.Activity;import android.app.Instrumentation;import android.os.Bundle;import android.location.Location;import android.content.Intent;import org.json.*;import com.insight.quantlife.*;
public class GapFixTest extends Instrumentation {
 MainHost host;int passed;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean b,String label)throws Exception{if(!b)throw new Exception(label);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+label+"\n");sendStatus(0,o);}
 int meters(JSONArray points)throws Exception{return Integer.parseInt(host.js("LifeTracks.summary("+points+").meters"));}
 @Override public void onStart(){Bundle out=new Bundle();try(TrackStore db=new TrackStore(getTargetContext())){
  host=new MainHost(this);host.open();JSONObject init=(JSONObject)host.call("init",new JSONObject());check(init.toString().contains("upgrade-1.1-note"),"Cover-install preserves learning record");check(init.getJSONArray("wikiPages").length()>0,"Existing Wiki preserved");check(init.getJSONObject("settings").getJSONObject("profiles").getJSONObject("custom").getBoolean("keyConfigured"),"Existing encrypted model key preserved");
  JSONObject day=(JSONObject)host.call("trackDay",new JSONObject().put("date","2026-10-08"));JSONArray points=day.getJSONArray("points");check(db.getReadableDatabase().getVersion()==3,"Schema2 upgrades to3 without removing raw history");check(day.getInt("totalPoints")==28&&points.length()==28,"All seeded raw positions retained");check(Math.abs(meters(points)-14)<=1,"218-second275m gap is excluded from distance; real14m walk retained");check(host.js("LifeTracks.summary("+points+").segments").equals("2"),"Screen segments split at short indoor gap");check(db.gpx("2026-10-08").split("<trkseg>",-1).length-1==2,"GPX splits exactly the same gap as screen");
  JSONObject diagnostic=db.diagnostics("2026-10-08");check(diagnostic.getJSONArray("rawPoints").length()==28&&diagnostic.getJSONObject("filtered").getJSONArray("points").length()==28,"Diagnostics preserves both original and displayed points");check(diagnostic.toString().contains("speedAccuracy")&&!diagnostic.toString().contains("local-test-only"),"Diagnostics includes speed uncertainty, no model key");check(diagnostic.getString("coordinateSystem").equals("WGS84")&&diagnostic.getString("mapProjection").equals("EPSG:3857"),"Coordinate reference is explicit and unchanged");
  String date="2026-10-09";db.deleteDay(date);long base=TrackStore.dayStart(date)+10*3600000;for(int i=0;i<10;i++){Location l=BeforeGapFixTest.p(base+i*5000,i*7,1.4f);JSONObject telemetry=new JSONObject();if(i==4||i==5)telemetry.put("satellitesUsed",2).put("gnssAgeMs",1000).put("meanCn0",15);db.add(l,"weak-fixture",telemetry);}JSONObject weak=db.day(date);check(weak.getInt("totalPoints")==10&&weak.getJSONArray("points").length()==8,"Weak signal retained raw for diagnosis but excluded from displayed route");check(weak.getJSONArray("points").getJSONObject(4).getBoolean("breakBefore"),"Weak signal leaves explicit native discontinuity");check(db.gpx(date).split("<trkseg>",-1).length-1==2,"Weak signal discontinuity propagated to GPX");check(db.diagnostics(date).getJSONArray("rawPoints").getJSONObject(4).getJSONObject("telemetry").getInt("satellitesUsed")==2,"GNSS quality retained in local diagnostics");
  date="2026-10-10";db.deleteDay(date);base=TrackStore.dayStart(date)+10*3600000;for(int i=0;i<=24;i++){double north=i<=6?i*5:i<=12?30:i<=18?30-(i-12)*5:0,east=i<=6?0:i<=12?(i-6)*5:i<=18?30:30-(i-18)*5;Location l=BeforeGapFixTest.p(base+i*5000,north,0);l.removeSpeed();l.setLongitude(121.47+east/(111195*Math.cos(Math.toRadians(l.getLatitude()))));db.add(l,"turn-fixture");}JSONArray turns=db.day(date).getJSONArray("points");check(meters(turns)>110,"Missing speed metadata preserves a120m turning walk");JSONObject last=turns.getJSONObject(turns.length()-1);check(Math.abs(last.getDouble("lat")-31.23)<.00001&&Math.abs(last.getDouble("lon")-121.47)<.00001,"Turning walk endpoint is not pinned to a stale corner");
  host.js("document.querySelector('[data-page=tracks]').click()");host.waitText("每天走过的地方");host.js("document.querySelector('#track-date').value='2026-10-08';document.querySelector('#track-date').dispatchEvent(new Event('change'))");check(host.waitText("0.01"),"Actual WebView renders corrected distance");check(host.waitText("超过60秒"),"Track page explains missing signal without pretending to know route");host.js("document.querySelector('#track-map').scrollIntoView({block:'start'})");host.screenshot("gap-fixed.png");
  host.js("document.querySelector('[data-page=settings]').click()");check(host.waitText("导出定位诊断"),"Raw diagnostic export available in Settings, not added to AI");host.js("document.querySelector('#track-diagnostics').click()");check(host.waitText("导出原始定位诊断"),"Sensitive diagnostic export requires disclosure and confirmation");host.js("document.querySelector('#confirm-cancel').click()");check(!((JSONObject)host.call("init",new JSONObject())).has("rawPoints"),"Raw location diagnostics not exposed to normal AI initialization");
  host.js("document.querySelector('#track-diagnostics').click();document.querySelector('#confirm-ok').click()");boolean pickerReady=false;for(int i=0;i<40;i++){android.view.accessibility.AccessibilityNodeInfo picker=getUiAutomation().getRootInActiveWindow();if(picker!=null&&picker.getPackageName()!=null&&picker.getPackageName().toString().contains("documentsui")){pickerReady=true;break;}Thread.sleep(100);}check(pickerReady,"Confirmed diagnostics opens Android document save picker");try(java.io.InputStream input=new android.os.ParcelFileDescriptor.AutoCloseInputStream(getUiAutomation().executeShellCommand("input keyevent 4"))){while(input.read()!=-1){}}Thread.sleep(300);check(db.day("2026-10-08").getInt("totalPoints")==28,"Canceling diagnostic save never alters stored GPS history");
  out.putString("stream","PASS: "+passed+" Android gap-fix and diagnostic checks.\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e+"\n");finish(Activity.RESULT_CANCELED,out);}}
}
