package com.insight.quantlife.tests;
import android.app.*;import android.os.Bundle;import com.insight.quantlife.*;import org.json.*;import java.net.*;import java.nio.charset.StandardCharsets;
public class LinkReaderTest extends Instrumentation {
 int passed,searches;void check(boolean b,String s)throws Exception{if(!b)throw new Exception(s);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+s+"\n");sendStatus(0,o);}
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 LinkReader.Page page(String s){return new LinkReader.Page(200,"","text/html; charset=UTF-8",s.getBytes(StandardCharsets.UTF_8));}
 @Override public void onStart(){Bundle out=new Bundle();try{
  for(String bad:new String[]{"file:///secret","http://127.0.0.1/","https://10.0.0.1/","https://localhost/","https://host.local/","https://user:secret@example.com/","https://example.com:9443/","https://example.com/?api_key=secret","https://example.com/?x=1&access_token=secret","https://example.com/\r\nHeader:x","https://[::1]/","https://2130706433/"}){boolean blocked=false;try{LinkReader.safeUrl(bad);}catch(Exception e){blocked=true;}check(blocked,"Reject unsafe URL "+bad.replaceAll("[\\r\\n]",""));}
  check(LinkReader.safeUrl("http://example.com/a?x=1#fragment").toString().equals("https://example.com/a?x=1"),"HTTP upgraded, fragments stripped");
  for(String ip:new String[]{"127.0.0.1","10.1.2.3","172.16.1.1","192.168.1.1","169.254.1.1","100.64.1.1","0.0.0.0","224.0.0.1","::1","fc00::1","fe80::1","2001:db8::1","64:ff9b::7f00:1"})check(!LinkReader.publicAddress(InetAddress.getByName(ip)),"Reject DNS nonpublic "+ip);
  check(LinkReader.publicAddress(InetAddress.getByName("1.1.1.1")),"Public IPv4 allowed");check(LinkReader.publicAddress(InetAddress.getByName("2606:4700:4700::1111")),"Native public IPv6 allowed");
  JSONObject article=LinkReader.parse("<title>fallback</title><meta content='测试 &amp; 标题' property='og:title'><meta name='author' content='作者甲'><meta property='og:type' content='article'><meta name='description' content='网上摘要'><script>steal secrets</script><style>private style</style><p>正文有限文本</p>","https://mp.weixin.qq.com/s/article");
  check(article.getString("title").equals("测试 & 标题"),"OG title precedence, entities, reversed attributes");check(article.getString("author").equals("作者甲"),"Author metadata extracted");check(article.getString("platform").equals("微信公众号")&&article.getString("contentType").equals("article"),"WeChat article metadata");check(article.getString("excerpt").contains("正文")&&!article.getString("excerpt").contains("steal")&&!article.getString("excerpt").contains("private style"),"Scripts/styles excluded from excerpts");
  check(LinkReader.parse("<title>视频</title>","https://www.bilibili.com/video/BV123").getString("contentType").equals("video"),"Bilibili path evidence detects video");check(LinkReader.parse("<title>书页</title>","https://book.douban.com/subject/123/").getString("contentType").equals("book"),"Book page path evidence");
  JSONObject book=LinkReader.parse("<script type='application/ld+json'>{\"@type\":\"Book\",\"name\":\"量化决策\",\"author\":{\"name\":\"测试作者\"}}</script>","https://example.com/item/1");check(book.getString("title").equals("量化决策")&&book.getString("author").equals("测试作者")&&book.getString("contentType").equals("book"),"JSON-LD book metadata");
  check(LinkReader.parse("<title>常规页</title>","https://example.com/item").getString("contentType").equals("other"),"Unknown type not fabricated");check(LinkReader.parse("<title>好</title><script>unfinished malicious text", "https://example.com/").getString("excerpt").equals("好"),"Truncated script excluded");
  JSONObject enabled=new JSONObject().put("enabled",true).put("apiKey","tvly-dummy-not-real");
  LinkReader.SearchTransport exact=(request,key)->{searches++;check(key.equals("tvly-dummy-not-real"),"Search receives only its dummy key");check(request.length()==6&&!request.has("messages")&&!request.has("records")&&!request.has("apiKey"),"Search payload excludes personal context and model keys");check(request.getString("query").equals("https://example.com/article/1"),"Search query is only requested URL");return new JSONObject().put("results",new JSONArray().put(new JSONObject().put("url","https://example.com/article/1?utm_source=x").put("title","搜索标题").put("content","搜索摘要不是个人笔记")));};
  LinkReader direct=new LinkReader((u,d)->page("<title>公开文章</title><meta property='og:type' content='article'>"),exact);JSONObject r=direct.resolve("https://example.com/article/1",enabled);check(r.getString("status").equals("metadata")&&searches==0,"Direct metadata preferred; no search charge");check(!r.has("durationMinutes")&&!r.has("note"),"Reader never creates time or personal notes");
  LinkReader failure=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),exact);r=failure.resolve("https://example.com/article/1",new JSONObject());check(r.getString("status").equals("unavailable")&&searches==0,"Disabled/missing search does not make request");r=failure.resolve("https://example.com/article/1",enabled);check(r.getString("status").equals("search_match")&&r.getString("title").equals("搜索标题"),"Exact same-page search fallback");check(r.getString("contentType").equals("article"),"Search match type from URL evidence");
  LinkReader unrelated=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),(q,k)->new JSONObject().put("results",new JSONArray().put(new JSONObject().put("url","https://example.com/other").put("title","其他页"))));check(unrelated.resolve("https://example.com/article/1",enabled).getString("title").isEmpty(),"Unrelated search hit cannot become original title");
  LinkReader searchError=new LinkReader((u,d)->new LinkReader.Page(403,"","",new byte[0]),(q,k)->{throw new Exception("SECRET MUST NOT ECHO");});r=searchError.resolve("https://example.com/article/1",enabled);check(r.getString("searchStatus").equals("failed")&&!r.toString().contains("SECRET"),"Search errors redact response details");
  LinkReader login=new LinkReader((u,d)->page("<title>Just a moment...</title>"),null);check(login.resolve("https://example.com/article/1",null).getString("title").isEmpty(),"Challenge page not accepted as title");
  LinkReader redirect=new LinkReader((u,d)->u.getPath().equals("/old")?new LinkReader.Page(302,"/article/1","",new byte[0]):page("<title>新页</title>"),null);check(redirect.resolve("https://example.com/old",null).getString("finalUrl").endsWith("/article/1"),"Public redirect supported");
  LinkReader unsafeRedirect=new LinkReader((u,d)->new LinkReader.Page(302,"http://127.0.0.1/","",new byte[0]),exact);int old=searches;check(unsafeRedirect.resolve("https://example.com/old",enabled).getString("status").equals("blocked")&&searches==old,"Private redirect blocked before follow or search");
  LinkReader dnsPrivate=new LinkReader((u,d)->{throw new SecurityException();},exact);check(dnsPrivate.resolve("https://example.com/old",enabled).getString("status").equals("blocked"),"Private DNS resolution fails closed");
  check(LinkReader.samePage("https://example.com/a?v=2&utm_source=x","http://example.com/a?v=2"),"Identity ignores tracking and protocol upgrade");check(!LinkReader.samePage("https://example.com/a?v=2","https://example.com/a?v=3"),"Different video IDs do not match");
  JSONObject request=LinkReader.searchRequest("https://example.com/a");check(!request.getBoolean("include_answer")&&!request.getBoolean("include_raw_content")&&request.getInt("max_results")==3,"Bounded search with generated answers disabled");
  check(LinkReader.searchResults(new JSONObject().put("results",new JSONArray().put(new JSONObject().put("url","http://127.0.0.1/").put("title","unsafe")))).length()==0,"Unsafe search result URL discarded");
  MainHost host=new MainHost(this);host.open();JSONObject settings=(JSONObject)host.call("saveLinkSettings",new JSONObject().put("settings",enabled));check(settings.getJSONObject("linkSearch").getBoolean("keyConfigured")&&!settings.toString().contains("tvly-dummy"),"Search key redacted from public settings");check(!getTargetContext().getSharedPreferences("secure",0).getString("settings","").contains("tvly-dummy"),"Search key encrypted at rest");host.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("enabled",false).put("apiKey","")));settings=(JSONObject)host.call("getSettings",new JSONObject());check(settings.getJSONObject("linkSearch").getBoolean("keyConfigured"),"Blank search key preserves previous secret");settings=(JSONObject)host.call("saveLinkSettings",new JSONObject().put("settings",new JSONObject().put("clearKey",true)));check(!settings.getJSONObject("linkSearch").getBoolean("keyConfigured"),"Explicit delete clears search key");
  JSONObject blocked=((JSONArray)host.call("readLinks",new JSONObject().put("urls",new JSONArray().put("http://127.0.0.1/")))).getJSONObject(0);check(blocked.getString("status").equals("blocked"),"Native readLinks bridge enforces URL policy");
  JSONObject real=((JSONArray)host.call("readLinks",new JSONObject().put("urls",new JSONArray().put("https://example.com/")))).getJSONObject(0);check(real.getString("status").equals("metadata")&&real.getString("title").equals("Example Domain"),"Real public HTTPS TLS/body read from Android (Example Domain)");
  out.putString("stream","PASS: "+passed+" native link/secret checks\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e);finish(Activity.RESULT_CANCELED,out);}}
}
