package com.insight.quantlife.tests;
import android.app.Activity;import android.app.Instrumentation;import android.os.Bundle;import android.os.SystemClock;import android.content.Intent;import android.location.*;import org.json.*;import com.insight.quantlife.*;
public class LiveGpsRefinementTest extends Instrumentation {
 MainHost host;LocationManager manager;TrackStore db;int passed;String date;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean b,String label)throws Exception{if(!b)throw new Exception(label);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+label+"\n");sendStatus(0,o);}
 JSONObject day()throws Exception{return (JSONObject)host.call("trackDay",new JSONObject().put("date",date));}
 void send(double meters,float speed)throws Exception{Location p=new Location("gps");p.setLatitude(31.23+meters/111195.0);p.setLongitude(121.47);p.setAccuracy(8);p.setSpeed(speed);p.setSpeedAccuracyMetersPerSecond(.15f);p.setTime(System.currentTimeMillis());p.setElapsedRealtimeNanos(SystemClock.elapsedRealtimeNanos());manager.setTestProviderLocation("gps",p);Thread.sleep(500);}
 int distance()throws Exception{return Integer.parseInt(host.js("LifeTracks.summary("+day().getJSONArray("points")+").meters"));}
 @Override public void onStart(){Bundle out=new Bundle();try{
  getTargetContext().stopService(new Intent(getTargetContext(),TrackingService.class));Thread.sleep(100);host=new MainHost(this);host.open();date=new java.text.SimpleDateFormat("yyyy-MM-dd",java.util.Locale.US).format(new java.util.Date());db=new TrackStore(getTargetContext());db.deleteDay(date);
  for(String permission:new String[]{android.Manifest.permission.ACCESS_FINE_LOCATION,android.Manifest.permission.ACCESS_COARSE_LOCATION,android.Manifest.permission.POST_NOTIFICATIONS})getUiAutomation().grantRuntimePermission(getTargetContext().getPackageName(),permission);
  manager=(LocationManager)getTargetContext().getSystemService(android.content.Context.LOCATION_SERVICE);manager.addTestProvider("gps",false,false,false,false,true,true,true,Criteria.POWER_LOW,Criteria.ACCURACY_FINE);manager.setTestProviderEnabled("gps",true);
  host.call("trackStart",new JSONObject());for(int i=0;i<30&&!TrackingService.running;i++)Thread.sleep(150);check(TrackingService.running,"Native GPS foreground service started");send(0,0);check(day().getInt("totalPoints")>=1,"Fresh GPS callback stored");
  Thread.sleep(5100);send(80,0);Thread.sleep(5100);send(0,0);check(day().getInt("totalPoints")>=3,"Actual five-second GPS callbacks stored without old 15-second throttle");check(distance()==0,"Actual zero-speed 80m drift and return do not count as movement");
  try(android.database.Cursor c=db.getReadableDatabase().rawQuery("SELECT speed,speed_accuracy,telemetry FROM points WHERE time>=? AND time<? ORDER BY time DESC LIMIT 1",new String[]{String.valueOf(TrackStore.dayStart(date)),String.valueOf(TrackStore.dayEnd(date))})){check(c.moveToFirst()&&!c.isNull(0)&&!c.isNull(1)&&!c.isNull(2),"GNSS speed, speed accuracy and fix age persist in selected-day SQLite");}
  Thread.sleep(5100);send(7,1.4f);check(Math.abs(distance()-7)<=1,"Seven-meter walking step is not discarded as accuracy noise");int before=day().getInt("totalPoints");
  Intent home=new Intent(Intent.ACTION_MAIN);home.addCategory(Intent.CATEGORY_HOME);home.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);getTargetContext().startActivity(home);getUiAutomation().executeShellCommand("input keyevent 223").close();Thread.sleep(5100);send(14,1.4f);check(TrackingService.running&&day().getInt("totalPoints")>before,"Five-second GPS callback continues with screen off and Activity in background");check(Math.abs(distance()-14)<=1,"Background walking step included in distance");
  getTargetContext().startService(new Intent(getTargetContext(),TrackingService.class).setAction(TrackingService.STOP));Thread.sleep(300);check(!TrackingService.running&&!day().getJSONObject("status").getBoolean("enabled"),"Notification pause stops collection");int paused=day().getInt("totalPoints");Thread.sleep(5100);send(21,1.4f);check(day().getInt("totalPoints")==paused,"Paused service cannot insert further callbacks");
  out.putString("stream","PASS: "+passed+" real LocationManager callback refinement checks.\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e+"\n");finish(Activity.RESULT_CANCELED,out);}finally{getTargetContext().stopService(new Intent(getTargetContext(),TrackingService.class));if(manager!=null)try{manager.removeTestProvider("gps");}catch(Exception ignored){}try{getUiAutomation().executeShellCommand("input keyevent 224").close();getUiAutomation().executeShellCommand("wm dismiss-keyguard").close();}catch(Exception ignored){}if(db!=null)db.close();}}
}
