package com.insight.quantlife.tests;
import android.app.Activity;import android.app.Instrumentation;import android.os.Bundle;import android.location.Location;import org.json.*;import com.insight.quantlife.*;import java.io.*;
public class SparseTrackTest extends Instrumentation{
 MainHost host;int passed;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean value,String title)throws Exception{if(!value)throw new Exception(title);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+title+"\n");sendStatus(0,o);}
 int meters(JSONArray p)throws Exception{return Integer.parseInt(host.js("LifeTracks.summary("+p+").meters"));}
 @Override public void onStart(){Bundle out=new Bundle();try(TrackStore db=new TrackStore(getTargetContext())){
  StringBuilder s=new StringBuilder();try(BufferedReader r=new BufferedReader(new InputStreamReader(getTargetContext().openFileInput("sparse-upgrade-fixture.json"),"UTF-8"))){String line;while((line=r.readLine())!=null)s.append(line);}JSONObject snapshot=new JSONObject(s.toString());
  host=new MainHost(this);host.open();JSONObject init=(JSONObject)host.call("init",new JSONObject());check(init.getJSONArray("records").length()==snapshot.getInt("learningCount"),"Cover upgrade keeps all learning/work records");check(init.getJSONArray("wikiPages").length()==snapshot.getInt("wikiCount"),"Cover upgrade keeps Wiki");check(init.getJSONObject("settings").toString().equals(snapshot.getJSONObject("settings").toString()),"Cover upgrade keeps model settings and configured-key status");
  JSONObject day=db.day("2026-10-11");JSONArray points=day.getJSONArray("points");check(db.getReadableDatabase().getVersion()==3&&day.getInt("filterVersion")==4,"Filter updates without database migration");check(day.getInt("totalPoints")==13&&points.length()==11,"All raw13 kept; unsafe network and poor samples not restored");check(snapshot.getString("oldMeters").equals("360")&&meters(points)==400,"Old360m pinned-tail bug recalculates to synthetic400m");check(db.gpx("2026-10-11").split("<trkseg>",-1).length-1==1,"Continuous31-second legacy GPX retains one observed segment");check(day.getJSONObject("quality").getInt("nonGpsPoints")==1&&day.getJSONObject("quality").getInt("poorAccuracyPoints")==1,"Native quality counters explain excluded source points");check(points.getJSONObject(10).has("reportedAccuracy"),"Displayed points carry original reported accuracy");check(db.diagnostics("2026-10-11").getJSONArray("rawPoints").length()==13,"Read-time repair never overwrites raw data");
  String date="2026-10-12";db.deleteDay(date);long base=TrackStore.dayStart(date)+12*3600000;for(int i=0;i<3;i++)db.add(BeforeGapFixTest.p(base+i*218000,i*275,1.4f),"isolated-fixture");JSONArray isolated=db.day(date).getJSONArray("points");check(isolated.length()==3&&meters(isolated)==0,"Three isolated fixes are kept, no invented550m journey");check(db.gpx(date).split("<trkseg>",-1).length-1==3,"GPX isolated segments agree with screen");
  host.js("window.__trackDots=[];window.__originalArc=CanvasRenderingContext2D.prototype.arc;CanvasRenderingContext2D.prototype.arc=function(x,y,r){if(this.canvas.id==='track-map')window.__trackDots.push(r);return window.__originalArc.apply(this,arguments)};document.querySelector('[data-page=tracks]').click()");host.waitText("每天走过的地方");host.js("document.querySelector('#track-date').value='2026-10-12';document.querySelector('#track-date').dispatchEvent(new Event('change'))");check(host.waitText("查看 2 处断点的时间"),"Real WebView explains each gap rather than silently omitting it");check(Integer.parseInt(host.js("document.querySelectorAll('[data-track-gap]').length"))==2,"Gap timestamps available as focus buttons");check(Integer.parseInt(host.js("window.__trackDots.filter(r=>r===3).length"))>=3,"Canvas renders all three singleton location dots");check(Integer.parseInt(host.js("window.__trackDots.filter(r=>r===4).length"))>=4,"Canvas marks all gap endpoints without drawing connectors");
  host.js("document.querySelector('#track-gap-list').open=true;document.querySelector('[data-track-gap]').click()");check(host.js("document.querySelector('#track-selected-point').innerText").contains("218秒"),"Selecting a gap focuses the map and explains218-second missing interval");host.js("document.querySelector('#track-map').scrollIntoView({block:'center'})");host.screenshot("sparse-gap-markers.png");
  host.js("document.querySelector('#track-date').value='2026-10-11';document.querySelector('#track-date').dispatchEvent(new Event('change'))");check(host.waitText("0.40"),"Historical corrected400m distance displayed");check(host.waitText("31 秒一采样"),"Sparse sampling warning distinguishes straight chords from actual roads");check(host.waitText("未展示 2 个原始点"),"Filtered-source reason shown without deleting raw fixes");check(!((JSONObject)host.call("init",new JSONObject())).has("points"),"Location data still absent from AI context");
  db.deleteDay("2026-10-14");db.deleteDay("2026-10-15");base=TrackStore.dayStart("2026-10-15")-120000;for(int i=0;i<5;i++){Location l=BeforeGapFixTest.p(base+i*31000,i*40,0);l.removeSpeed();l.removeSpeedAccuracy();db.add(l,"midnight-fixture");}JSONArray midnight=db.day("2026-10-15").getJSONArray("points");check(midnight.length()==1&&Math.abs(midnight.getJSONObject(0).getDouble("lat")-(31.23+160/111195.0))<.00001,"Midnight query retains sufficient sparse history context instead of resetting confirmed motion");
  out.putString("stream","PASS: "+passed+" sparse-history cover upgrade and WebView checks.\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){out.putString("stream","FAIL after "+passed+": "+e+"\n");finish(Activity.RESULT_CANCELED,out);}}
}
