package com.insight.quantlife.tests;
import android.app.Activity;import android.app.Instrumentation;import android.os.Bundle;import android.location.Location;import android.database.sqlite.SQLiteDatabase;import android.database.Cursor;import android.content.ContentValues;import android.graphics.Bitmap;import android.graphics.Canvas;import android.graphics.Paint;import android.graphics.Color;import android.net.Uri;import java.io.*;import org.json.*;import com.insight.quantlife.*;
public class TrackRefinementTest extends Instrumentation {
 MainHost host;TrackStore store;int passed;
 @Override public void onCreate(Bundle b){super.onCreate(b);start();}
 void check(boolean b,String label)throws Exception{if(!b)throw new Exception(label);passed++;Bundle o=new Bundle();o.putString("stream","PASS "+label+"\n");sendStatus(0,o);}
 JSONObject day(String date)throws Exception{return (JSONObject)host.call("trackDay",new JSONObject().put("date",date));}
 Location p(long time,double meters,float speed){Location l=new Location("gps");l.setTime(time);l.setLatitude(31.23+meters/111195.0);l.setLongitude(121.47);l.setAccuracy(8);l.setSpeed(speed);l.setSpeedAccuracyMetersPerSecond(0.15f);return l;}
 int meters(JSONArray points)throws Exception{return Integer.parseInt(host.js("LifeTracks.summary("+points+").meters"));}
 @Override public void onStart(){Bundle out=new Bundle();try{
  host=new MainHost(this);host.open();JSONObject init=(JSONObject)host.call("init",new JSONObject());check(init.toString().contains("upgrade-1.1-note"),"1.2 cover-install retains learning notes");check(init.getJSONArray("wikiPages").length()>0,"Existing Wiki preserved");check(init.getJSONObject("settings").getJSONObject("profiles").getJSONObject("custom").getBoolean("keyConfigured"),"Encrypted model key preserved");
  JSONObject legacy=day("2026-10-05");store=new TrackStore(getTargetContext());check(store.getReadableDatabase().getVersion()==3,"Track schema1 upgraded additively to schema3");JSONArray old=legacy.getJSONArray("points"),drift=new JSONArray();for(int i=0;i<old.length();i++)if(old.getJSONObject(i).getString("session").equals("legacy-drift"))drift.put(old.getJSONObject(i));check(drift.length()>0&&meters(drift)==0,"Legacy speedless stationary drift recalculated to zero distance");try(Cursor c=store.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM points WHERE session='legacy-drift'",null)){c.moveToFirst();check(c.getInt(0)==60,"Original raw history is retained, not destructively rewritten");}
  String date="2026-10-08";store.deleteDay(date);long base=TrackStore.dayStart(date)+9*3600000;
  for(int i=0;i<360;i++)store.add(p(base+i*5000,i==0?0:Math.sin(i*.7)*150,0),"static");JSONObject still=day(date);check(meters(still.getJSONArray("points"))==0,"SQLite plus WebView do not count 30-minute repeated stationary drift");
  store.deleteDay(date);for(int i=0;i<=120;i++)store.add(p(base+i*5000,i*7,1.4f),"walking");JSONArray walk=day(date).getJSONArray("points");check(walk.length()==121&&Math.abs(meters(walk)-840)<2,"Walking small five-second steps are retained in UI distance");
  for(int i=0;i<=120;i++)store.add(p(base+1200000+i*5000,1000+i*25,5),"cycling");check(Math.abs(meters(day(date).getJSONArray("points"))-3840)<3,"Cycling distance included without joining separate sessions");
  for(int i=0;i<=120;i++)store.add(p(base+2400000+i*5000,5000+i*100,20),"vehicle");check(Math.abs(meters(day(date).getJSONArray("points"))-15840)<4,"Vehicle distance included in filtered trajectory");
  Location inaccurate=p(base+3600000,18000,0);inaccurate.setAccuracy(60);store.add(inaccurate,"poor");check(day(date).getInt("totalPoints")>day(date).getJSONArray("points").length(),"Low-accuracy raw fix cannot add display distance");
  String gpx=store.gpx(date);check(gpx.split("<trkpt ",-1).length-1==day(date).getJSONArray("points").length(),"GPX uses the same denoised coordinates as the screen");check(gpx.split("<trkseg>",-1).length-1==3,"GPX splits walking, cycling and vehicle sessions");
  check(day(date).getJSONObject("status").getString("mapMode").equals("offline"),"Upgrade defaults to offline map with no background tile requests");
  host.js("document.querySelector('[data-page=tracks]').click()");check(host.waitText("每天走过的地方"),"Simplified track screen renders");host.js("document.querySelector('#track-date').value='2026-10-08';document.querySelector('#track-date').dispatchEvent(new Event('change'))");check(host.waitText("15.84"),"Filtered combined distance displayed");check(!host.js("document.body.innerText").contains("估算停留")&&!host.js("document.body.innerText").contains("让小米后台尽量稳定"),"Stop estimates and Xiaomi helper panel removed");check(host.js("document.querySelector('#track-battery')===null&&document.querySelector('#track-permissions')===null&&document.querySelector('#track-map-key')===null").equals("true"),"Battery shortcuts and map-key form removed");
  host.js("document.querySelector('#track-map-mode').value='online';document.querySelector('#track-map-mode').dispatchEvent(new Event('change'))");check(host.waitText("加载在线 OSM 地图"),"Online switch requires explicit map privacy consent");host.js("document.querySelector('#confirm-cancel').click()");check(day(date).getJSONObject("status").getString("mapMode").equals("offline"),"Canceling online map stays fully offline");
  boolean invalid=false;try{host.call("trackConfig",new JSONObject().put("mapMode","online"));}catch(Exception e){invalid=true;}check(invalid,"Native bridge cannot enable online mode without consent");
  File fixture=new File(getTargetContext().getFilesDir(),"test-offline-map.mbtiles");if(fixture.exists())fixture.delete();
  Bitmap bitmap=Bitmap.createBitmap(256,256,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(bitmap);canvas.drawColor(Color.rgb(225,234,215));Paint pen=new Paint();pen.setColor(Color.WHITE);pen.setStrokeWidth(10);canvas.drawLine(0,128,256,128,pen);canvas.drawLine(128,0,128,256,pen);pen.setColor(Color.DKGRAY);pen.setTextSize(20);canvas.drawText("SYNTHETIC QA",30,60,pen);ByteArrayOutputStream image=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.PNG,100,image);bitmap.recycle();
  int z=16,x=(int)Math.floor((121.47+180)/360*(1<<z));double lat=Math.toRadians(31.23);int y=(int)Math.floor((1-Math.log(Math.tan(lat)+1/Math.cos(lat))/Math.PI)/2*(1<<z));
  try(SQLiteDatabase db=SQLiteDatabase.openOrCreateDatabase(fixture,null)){db.execSQL("CREATE TABLE metadata(name TEXT,value TEXT)");db.execSQL("INSERT INTO metadata VALUES('format','png'),('name','Synthetic QA, not a street map'),('attribution','Synthetic test only'),('scheme','tms')");db.execSQL("CREATE TABLE tiles(zoom_level INTEGER,tile_column INTEGER,tile_row INTEGER,tile_data BLOB)");for(int dx=-2;dx<=2;dx++)for(int dy=-2;dy<=2;dy++){ContentValues v=new ContentValues();v.put("zoom_level",z);v.put("tile_column",x+dx);v.put("tile_row",(1<<z)-1-(y+dy));v.put("tile_data",image.toByteArray());db.insertOrThrow("tiles",null,v);}}
  OfflineMap.importFile(getTargetContext(),Uri.fromFile(fixture));check(OfflineMap.info(getTargetContext()).getBoolean("configured"),"Raster MBTiles imported into private local storage");JSONObject tile=(JSONObject)host.call("trackTile",new JSONObject().put("z",z).put("x",x).put("y",y));check(tile.getString("data").startsWith("data:image/png;base64,"),"XYZ-to-TMS conversion reads local PNG without key or online consent");
  boolean missing=false;try{host.call("trackTile",new JSONObject().put("z",2).put("x",0).put("y",0));}catch(Exception e){missing=true;}check(missing,"Missing offline coverage returns local fallback instead of networking");
  File bad=new File(getTargetContext().getFilesDir(),"test-bad-map.mbtiles");try(FileOutputStream f=new FileOutputStream(bad)){f.write("not sqlite".getBytes("UTF-8"));}invalid=false;try{OfflineMap.importFile(getTargetContext(),Uri.fromFile(bad));}catch(Exception e){invalid=true;}check(invalid&&OfflineMap.tile(getTargetContext(),z,x,y)!=null,"Invalid map import preserves existing offline map");
  host.js("TrackUI.mapImported();document.querySelector('#track-date').value='2026-10-08';document.querySelector('#track-date').dispatchEvent(new Event('change'))");Thread.sleep(500);host.js("document.querySelector('#track-fit').click();document.querySelector('#track-zoom-in').click();document.querySelector('#track-zoom-in').click();document.querySelector('#track-zoom-in').click();document.querySelector('#track-zoom-in').click()");
  host.js("document.querySelector('[data-page=settings]').click()");check(host.waitText("轨迹数据"),"Track management moved to Settings");check(host.js("!!document.querySelector('#track-export')&&!!document.querySelector('#track-delete')&&!!document.querySelector('#track-reboot')").equals("true"),"Export delete and reboot preference remain available in Settings");
  host.js("document.querySelector('[data-page=tracks]').click()");host.js("document.querySelector('#track-date').value='2026-10-08';document.querySelector('#track-date').dispatchEvent(new Event('change'))");Thread.sleep(500);host.screenshot("tracks-refined.png");
  check(!((JSONObject)host.call("init",new JSONObject())).has("points"),"Tracking data remains excluded from AI context");
  out.putString("stream","\nPASS: "+passed+" refinement upgrade, GPS distance and offline map checks.\n");finish(Activity.RESULT_OK,out);
 }catch(Throwable e){String body="";try{body=host.js("document.body.innerText");}catch(Exception ignored){}out.putString("stream","FAIL after "+passed+": "+e+"\n"+body+"\n");finish(Activity.RESULT_CANCELED,out);}finally{if(store!=null)store.close();}}
}
