const {test}=require('node:test');const assert=require('node:assert/strict');const D=require('../app/src/main/assets/domain.js');const W=require('../app/src/main/assets/wiki.js');
const now=new Date('2026-10-05T12:00:00');
const learning=(id,date='2026-09-06',duration=60)=>({id,type:'learning',date,title:'JEV模型应用 '+id,note:'JEV应用实践',tags:['JEV'],platform:'知乎',contentType:'article',durationMinutes:duration});
const plan={intent:'insight',topic:'JEV',keywords:['JEV模型'],dateStart:'',dateEnd:''};
test('上个月6号、六号、中文年月日以及整月的精确解析',()=>{assert.equal(D.questionPeriod('上个月6号学了什么',now).start,'2026-09-06');assert.equal(D.questionPeriod('上个月六号',now).end,'2026-09-06');assert.equal(D.questionPeriod('2026年九月六日',now).start,'2026-09-06');assert.equal(D.questionPeriod('9月6日',now).start,'2026-09-06');assert.equal(D.questionPeriod('上个月',now).end,'2026-09-30');assert.equal(D.questionPeriod('上个月6号',new Date('2026-01-05')).start,'2025-12-06');assert.throws(()=>D.questionPeriod('2026年2月30日',now),/不存在/);assert.throws(()=>D.questionPeriod('上个月31号',now),/不存在/);});
test('日期范围闭区间与非法日期不回退到全历史',()=>{const p=D.questionPeriod('2026-09-06至2026-09-08',now);assert.equal(p.end,'2026-09-08');assert.equal(p.b-Date.parse('2026-09-06T00:00:00'),3*86400000);assert.throws(()=>D.questionPeriod('2026-02-30',now),/不存在/);assert.throws(()=>D.questionPeriod('2026-09-08至2026-09-06',now),/早于/);});
test('上月某日全量学习与跨夜工作精确汇总，不混入别的天',()=>{const records=[learning('a'),learning('b','2026-09-07',999),{id:'night',type:'work',date:'2026-09-05',title:'夜班',workStart:'2026-09-05T22:00:00',workEnd:'2026-09-06T06:00:00',breaks:[{start:'2026-09-05T23:30:00',end:'2026-09-06T00:30:00'}]}];const c=W.context(records,[],'上个月6号学习和工作多久',{...plan,intent:'history',topic:''},now);assert.equal(c.period,'2026-09-06 至 2026-09-06');assert.equal(c.summary.learningMinutes,60);assert.equal(c.summary.workMinutes,330);assert.equal(c.summary.restMinutes,30);assert.equal(c.summary.totalMatchingRecords,2);});
test('10条记录50小时只是个人阶段性自评轨迹，主题统计不混入别的领域',()=>{const records=Array.from({length:10},(_,i)=>learning('jev-'+i,'2026-09-'+String(i+1).padStart(2,'0'),300));records[9].masteryLevel='proficient';records[9].evidenceType='practice';records[9].evidenceNote='独立完成案例';records.push({...learning('other'),title:'摄影技巧',note:'摄影',tags:['摄影'],durationMinutes:9999});const c=W.context(records,[],'分析JEV模型应用的熟练度',plan,now);assert.equal(c.topicSummary.recordCount,10);assert.equal(c.topicSummary.learningMinutes,3000);assert.equal(c.topicSummary.milestones[0].cumulativeRecords,10);assert.equal(c.topicSummary.milestones[0].cumulativeMinutes,3000);assert.equal(c.topicSummary.milestones[0].evidenceType,'practice');assert.equal(c.records.length,10);});
test('没有掌握程度标记时不存在推断出的熟练里程碑',()=>{const stats=W.topicStats([learning('a',undefined,3000)]);assert.equal(stats.milestones.length,0);assert.match(stats.evidenceCaveat,/不能/);});
test('新Wiki别名扩展索引范围但不伪称读过新来源，新增别名记录触发失效',()=>{
 const a=learning('a'),b={...learning('b'),title:'缩写甲实践',tags:[],note:'缩写甲'};
 const p=W.indexPage(W.validatePage({summary:'摘要',aliases:['缩写甲'],concepts:[],sourceIds:['a']},[a],'JEV'),[a,b],[]);
 assert.equal(p.partial,true);assert.deepEqual(p.sourceIds,['a']);assert.equal(p.stats.recordCount,2);assert.equal(W.isStale(p,[a,b]),false);
 assert.equal(W.context([a,b],[p],'总结JEV',plan,now).topicSummary.recordCount,2);
 assert.equal(W.isStale(p,[a,b,{...b,id:'c'}]),true);
});
test('跨夜班次日期序列仅包含请求日',()=>{
 const r={id:'w',type:'work',date:'2026-09-05',title:'夜班',workStart:'2026-09-05T22:00:00',workEnd:'2026-09-06T06:00:00',breaks:[]};
 assert.deepEqual(W.context([r],[],'上个月6号',{...plan,intent:'history',topic:''},now).dailySeries.map(d=>d.date),['2026-09-06']);
});
test('重复学习同内容区分记录次数与内容数',()=>{const a=learning('a');const b={...a,id:'b',date:'2026-09-07'};assert.equal(W.topicStats([a,b]).recordCount,2);assert.equal(W.topicStats([a,b]).uniqueContents,1);});
test('LLM Wiki概念引用校验、来源修改/增加/删除的失效',()=>{const sources=[learning('a')];const page=W.validatePage({summary:'笔记摘要',aliases:['JEV模型'],concepts:[{title:'应用',description:'实践要点',sourceIds:['a']}],sourceIds:['a']},sources,'JEV');assert.equal(W.isStale(page,sources),false);assert.equal(W.isStale(page,[{...sources[0],note:'新笔记'}]),true);assert.equal(W.isStale(page,[...sources,learning('b')]),true);assert.equal(W.isStale(page,[]),true);assert.throws(()=>W.validatePage({...page,concepts:[{title:'伪造',description:'x',sourceIds:['fake']}]},sources,'JEV'),/真实/);});
test('过期Wiki不把旧摘要注入聊天上下文',()=>{const sources=[learning('a')],page=W.validatePage({summary:'旧结论',aliases:[],concepts:[],sourceIds:['a']},sources,'JEV');const c=W.context([{...sources[0],note:'完全不同的新内容'}],[page],'回顾JEV笔记',plan,now);assert.equal(c.wikiPages[0].stale,true);assert.equal(c.wikiPages[0].summary,'');});
test('指定历史日期不混入跨日期Wiki摘要',()=>{const sources=[learning('a'),learning('b','2026-10-01')],page=W.validatePage({summary:'混合两天知识',aliases:[],concepts:[],sourceIds:['a','b']},sources,'JEV');assert.equal(W.context(sources,[page],'上个月6号学了什么',{...plan,intent:'history'},now).wikiPages.length,0);});
test('规划器提供额外日期格式，显式本地日期优先于模型错误日期',()=>{const c=W.context([learning('a')],[],'上个月6号', {...plan,dateStart:'2026-10-05',dateEnd:'2026-10-05'},now);assert.equal(c.period,'2026-09-06 至 2026-09-06');assert.throws(()=>W.validatePlan({...plan,dateStart:'2026-02-30',dateEnd:'2026-02-30'}),/不存在/);});
test('Wiki分批内容限制和来源覆盖数量',()=>{const records=Array.from({length:45},(_,i)=>({...learning(String(i)),note:'知识'.repeat(5000)}));const batches=W.compilerBatches(records);assert.ok(batches.length>2);assert.equal(batches.flat().length,45);assert.ok(batches.every(b=>b.length<=20&&b.every(r=>r.note.length<=6000)));});
