plugins { id 'com.android.application' }
android {
    namespace 'com.insight.quantlife'
    compileSdk 35
    defaultConfig {
        applicationId 'com.insight.quantlife'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.4.3'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
