// Read-only trajectory audit. Prints relative meters, not users' absolute coordinates.
const fs=require('node:fs'),T=require('../app/src/main/assets/tracks.js');
const path=process.argv[2],from=process.argv[3]||'',to=process.argv[4]||'';
const text=fs.readFileSync(path,'utf8'),parts=[...text.matchAll(/<trkseg>([\s\S]*?)<\/trkseg>/g)].map((m,i)=>[...m[1].matchAll(/<trkpt\s+lat="([\d.+-]+)"\s+lon="([\d.+-]+)"[^>]*>[\s\S]*?<time>([^<]+)<\/time>[\s\S]*?<\/trkpt>/g)].map(p=>({lat:+p[1],lon:+p[2],time:Date.parse(p[3]),session:String(i)})));
const clock=t=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'medium'}).format(t);
let count=0,duplicates=0,total=0,largest=0,intervals=[],edges=0;
for(const part of parts){count+=part.length;for(let i=1;i<part.length;i++){const a=part[i-1],b=part[i],d=T.distance(a,b),dt=(b.time-a.time)/1000;total+=d;largest=Math.max(largest,d);intervals.push(dt);edges++;if(d<.01)duplicates++;}}
intervals.sort((a,b)=>a-b);const all=parts.flat();console.log(JSON.stringify({file:path.split(/[\/\\]/).at(-1),segments:parts.length,points:count,from:all[0]&&clock(all[0].time),to:all.at(-1)&&clock(all.at(-1).time),meters:Math.round(total),repeatedPositionEdges:duplicates,edges,medianIntervalSeconds:intervals[Math.floor(intervals.length/2)],largestEdgeMeters:Math.round(largest)},null,2));
const newView=T.summary(all.map(p=>({...p,accuracy:8,denoised:true})));console.log(JSON.stringify({renderingOnlyWith60SecondGapRule:{meters:newView.meters,segments:newView.segments},note:'This is a read-only display-rule comparison of already-filtered GPX, not a reconstruction of raw GPS or the actual route.'}));
if(from){const selected=all.filter(p=>clock(p.time).slice(11)>=from&&(!to||clock(p.time).slice(11)<=to));if(selected.length){const origin=selected[0];let previous=null;for(const p of selected){if(previous&&T.distance(previous,p)<.01)continue;console.log(JSON.stringify({time:clock(p.time),east:Math.round((p.lon-origin.lon)*111195*Math.cos(origin.lat*Math.PI/180)),north:Math.round((p.lat-origin.lat)*111195),metersFromPrevious:previous?Math.round(T.distance(previous,p)):0,secondsFromPrevious:previous?(p.time-previous.time)/1000:0,segment:p.session}));previous=p;}}}
for(const part of parts)for(let i=1;i<part.length;i++){const a=part[i-1],b=part[i],d=T.distance(a,b),dt=(b.time-a.time)/1000;if(d>30&&(!from||(clock(b.time).slice(11)>=from&&(!to||clock(b.time).slice(11)<=to))))console.log(JSON.stringify({edgeStart:clock(a.time),edgeEnd:clock(b.time),meters:Math.round(d),seconds:dt,metersPerSecond:+(d/dt).toFixed(2)}));}
